export const bundledLocalizations = {
    "de-DE": {
        "h.ld": "[instantgram] Sprache: de-DE\nWeitere Informationen zu den verfügbaren Sprachen findest du auf https://saschaheim.github.io/instantgram",
        "a.wo": "Funktioniert nur auf instagram.com",
        "a.nf": "Hast du einen Instagram-Post geöffnet? Zum Beispiel:",
        "a.ie": "Dieses Medium wird noch nicht unterstützt.",
        "ms.t": "Einstellungen",
        "ms.a": "<span class=\"sx\">Neu:</span> Monetarisierte Beiträge werden derzeit nicht unterstützt. Einige Änderungen gelten sofort; andere erst nach erneutem Öffnen des Bookmarklets.",
        "ms.g": "Allgemein",
        "msg.t2": "Download in neuem Tab",
        "msg.d2": "Der Download wird in einem neuen Tab geöffnet",
        "msg.t3": "Slideshow an/aus",
        "msg.d3": "Aktiviert oder deaktiviert die automatische Slideshow",
        "msg.t4": "Dateinamenformat ändern",
        "msg.d4": "Hier kannst du das Dateinamenformat für Downloads ändern.\nDas Standardformat ist:\n{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "msg.t5": "Videos stummschalten",
        "msg.d5": "Post-, Feed- und Reel-Videos werden stumm geöffnet",
        "msg.t6": "Automatisch vergrößern",
        "msg.d6": "Vergrößert das Medienfenster nach dem Öffnen automatisch",
        "mss.t1": "Stummschalten",
        "mss.d1": "Stories werden stumm geöffnet",
        "mss.t2": "Beim Öffnen pausieren",
        "mss.d2": "Stories werden beim Öffnen pausiert",
        "mss.t3": "Einzeln anzeigen",
        "mss.d3": "Stories werden beim Öffnen einzeln angezeigt",
        "d": "Download",
        "l": "Suche nach Medien...",
        "s": "Speichern",
        "sd": "Gespeichert",
        "c": "Schließen",
        "u.t": "Update verfügbar",
        "u.i": "[instantgram] ist veraltet. Bitte prüfe https://saschaheim.github.io/instantgram auf verfügbare Updates.",
        "u.v": "[instantgram] Installierte Version: ${data.version} | Neues Update: ${data.onlineVersion}",
        "modules.update@update_successful": "[instantgram] Update-Prüfung erfolgreich.",
        "ad": "Gesponsert"
    },
    "es-AR": {
        "h.ld": "[instantgram] Idioma: es-AR\nPara más información sobre los idiomas disponibles, visita https://saschaheim.github.io/instantgram",
        "a.wo": "Funciona solo en instagram.com",
        "a.nf": "¿Abriste una publicación de Instagram? Por ejemplo:",
        "a.ie": "Este contenido aún no es compatible.",
        "ms.t": "Configuración",
        "ms.a": "<span class=\"sx\">Nuevo:</span> Las publicaciones monetizadas no son compatibles actualmente. Algunos cambios se aplican de inmediato; otros requieren volver a abrir el bookmarklet.",
        "ms.g": "General",
        "msg.t2": "Descarga en nueva pestaña",
        "msg.d2": "La descarga se abrirá en una nueva pestaña",
        "msg.t3": "Presentación activada/desactivada",
        "msg.d3": "Activa o desactiva la presentación automática",
        "msg.t4": "Cambiar el formato del nombre de archivo",
        "msg.d4": "Cambia aquí el formato del nombre de archivo para las descargas.\nEl formato predeterminado es:\n{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "msg.t5": "Silenciar videos",
        "msg.d5": "Los videos de publicaciones, el feed y reels se abren silenciados",
        "msg.t6": "Expandir automáticamente",
        "msg.d6": "Expande automáticamente la ventana multimedia después de abrirla",
        "mss.t1": "Silenciar",
        "mss.d1": "Las historias se abren silenciadas",
        "mss.t2": "Pausar al abrir",
        "mss.d2": "Las historias se pausan al abrirse",
        "mss.t3": "Mostrar individualmente",
        "mss.d3": "Las historias se muestran individualmente al abrirse",
        "d": "Descargar",
        "l": "Buscando medios...",
        "s": "Guardar",
        "sd": "Guardado",
        "c": "Cerrar",
        "u.t": "Actualización disponible",
        "u.i": "[instantgram] está desactualizado. Visita https://saschaheim.github.io/instantgram para ver las actualizaciones disponibles.",
        "u.v": "[instantgram] Versión instalada: ${data.version} | Nueva actualización: ${data.onlineVersion}",
        "modules.update@update_successful": "[instantgram] Comprobación de actualización completada.",
        "ad": "Patrocinado"
    },
    "pt-BR": {
        "h.ld": "[instantgram] Idioma: pt-BR\nPara mais informações sobre os idiomas disponíveis, acesse https://saschaheim.github.io/instantgram",
        "a.wo": "Funciona apenas em instagram.com",
        "a.nf": "Você abriu uma publicação do Instagram? Por exemplo:",
        "a.ie": "Este conteúdo ainda não é suportado.",
        "ms.t": "Configurações",
        "ms.a": "<span class=\"sx\">Novo:</span> Publicações monetizadas não são suportadas no momento. Algumas alterações são aplicadas imediatamente; outras exigem reabrir o bookmarklet.",
        "ms.g": "Geral",
        "msg.t2": "Download em nova aba",
        "msg.d2": "O download será aberto em uma nova aba",
        "msg.t3": "Slideshow ligado/desligado",
        "msg.d3": "Ativa ou desativa o slideshow automático",
        "msg.t4": "Alterar formato do nome do arquivo",
        "msg.d4": "Altere aqui o formato do nome dos downloads.\nO formato padrão é:\n{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "msg.t5": "Silenciar vídeos",
        "msg.d5": "Vídeos de publicações, feed e reels são abertos sem som",
        "msg.t6": "Expandir automaticamente",
        "msg.d6": "Expande automaticamente a janela de mídia após abri-la",
        "mss.t1": "Silenciar",
        "mss.d1": "Os stories são abertos sem som",
        "mss.t2": "Pausar ao abrir",
        "mss.d2": "Os stories são pausados ao abrir",
        "mss.t3": "Exibir individualmente",
        "mss.d3": "Os stories são exibidos individualmente ao abrir",
        "d": "Baixar",
        "l": "Buscando mídia...",
        "s": "Salvar",
        "sd": "Salvo",
        "c": "Fechar",
        "u.t": "Atualização disponível",
        "u.i": "[instantgram] está desatualizado. Acesse https://saschaheim.github.io/instantgram para ver as atualizações disponíveis.",
        "u.v": "[instantgram] Versão instalada: ${data.version} | Nova atualização: ${data.onlineVersion}",
        "modules.update@update_successful": "[instantgram] Verificação de atualização concluída.",
        "ad": "Patrocinado"
    }
} as const;
