const locale = process.env.LOCALE || "en-US";

const enUS = {
    "h.ld": "[instantgram] language: en-US\nFor more information about available languages please check https://saschaheim.github.io/instantgram",
    "a.wo": "Works only on instagram.com",
    "a.nf": "Did you open any Instagram post? Like for example",
    "a.ie": "This media isn't supported yet.",
    "ms.t": "Settings",
    "ms.a": "<span class=\"sx\">New:</span> Some changes apply immediately. Others require reopening the bookmarklet.",
    "ms.g": "General",
    "msg.t1": "Enable monetized posts",
    "msg.d1": "Ad blockers must be deactivated",
    "msg.t2": "Open download in new tab",
    "msg.d2": "The download will be opened in a new tab",
    "msg.t3": "Slideshow on/off",
    "msg.d3": "Enable or disable the automatic slideshow",
    "msg.t4": "Change file name format for downloads",
    "msg.d4": "Change the file name format for the downloads here<br/>The default format is<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
    "msg.t5": "Mute videos",
    "msg.d5": "Post, feed and reel videos are muted when opened",
    "msg.t6": "Auto expand",
    "msg.d6": "Automatically expands the media modal after opening",
    "mss.t1": "Mute stories",
    "mss.d1": "Stories are muted when opened",
    "mss.t2": "Pause stories when opening",
    "mss.d2": "Stories are paused when opened",
    "mss.t3": "Display stories individually",
    "mss.d3": "Stories are displayed individually when opened",
    "d": "Download",
    "l": "Searching for media...",
    "s": "Save",
    "sd": "Saved",
    "c": "Close",
    "u.t": "Update available",
    "u.i": "[instantgram] is outdated. Please check https://saschaheim.github.io/instantgram for available updates.",
    "u.v": "[instantgram] Installed version: ${data.version} | New update: ${data.onlineVersion}",
    "modules.update@update_successful": "[instantgram] Update check successful.",
    "ad": "Sponsored"
} as const;

export type LocalizationKey = keyof typeof enUS;
type LocalizationDictionary = Record<LocalizationKey, string>;

const deDE: LocalizationDictionary = {
    "h.ld": "[instantgram] Sprache: de-DE\nWeitere Informationen zu den verfugbaren Sprachen findest du auf https://saschaheim.github.io/instantgram",
    "a.wo": "Funktioniert nur auf instagram.com",
    "a.nf": "Hast du einen Instagram-Post geoffnet? Zum Beispiel",
    "a.ie": "Dieses Medium wird noch nicht unterstutzt.",
    "ms.t": "Einstellungen",
    "ms.a": "<span class=\"sx\">Neu:</span> Einige Anderungen gelten sofort. Andere werden erst beim erneuten Offnen des Bookmarklets ubernommen.",
    "ms.g": "Allgemein",
    "msg.t1": "Monetarisierte Beitrage anzeigen",
    "msg.d1": "Adblocker mussen deaktiviert sein",
    "msg.t2": "Download in neuem Tab offnen",
    "msg.d2": "Der Download wird in einem neuen Tab geoffnet",
    "msg.t3": "Slideshow an/aus",
    "msg.d3": "Aktiviert oder deaktiviert die automatische Slideshow",
    "msg.t4": "Dateinamenformat fur Downloads andern",
    "msg.d4": "Hier kannst du das Dateinamenformat fur Downloads andern<br/>Das Standardformat ist<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
    "msg.t5": "Videos stummschalten",
    "msg.d5": "Post-, Feed- und Reel-Videos werden stumm geoffnet",
    "msg.t6": "Automatisch vergrosern",
    "msg.d6": "Offnet das Medien-Modal nach dem Start automatisch vergrossert",
    "mss.t1": "Stories stummschalten",
    "mss.d1": "Stories werden stumm geoffnet",
    "mss.t2": "Stories beim Offnen pausieren",
    "mss.d2": "Stories werden beim Offnen pausiert",
    "mss.t3": "Stories einzeln anzeigen",
    "mss.d3": "Stories werden beim Offnen einzeln angezeigt",
    "d": "Download",
    "l": "Suche nach Medien...",
    "s": "Speichern",
    "sd": "Gespeichert",
    "c": "Schliessen",
    "u.t": "Update verfugbar",
    "u.i": "[instantgram] ist veraltet. Bitte prufe https://saschaheim.github.io/instantgram auf verfugbare Updates.",
    "u.v": "[instantgram] Installierte Version: ${data.version} | Neues Update: ${data.onlineVersion}",
    "modules.update@update_successful": "[instantgram] Update-Prufung erfolgreich.",
    "ad": "Gesponsert"
};

const esAR: LocalizationDictionary = {
    "h.ld": "[instantgram] idioma: es-AR\nPara mas informacion sobre los idiomas disponibles visita https://saschaheim.github.io/instantgram",
    "a.wo": "Funciona solo en instagram.com",
    "a.nf": "Abriste alguna publicacion de Instagram? Por ejemplo",
    "a.ie": "Este contenido aun no es compatible.",
    "ms.t": "Configuracion",
    "ms.a": "<span class=\"sx\">Nuevo:</span> Algunos cambios se aplican de inmediato. Otros requieren volver a abrir el bookmarklet.",
    "ms.g": "General",
    "msg.t1": "Habilitar publicaciones monetizadas",
    "msg.d1": "Los bloqueadores de anuncios deben estar desactivados",
    "msg.t2": "Abrir descarga en una nueva pestana",
    "msg.d2": "La descarga se abrira en una nueva pestana",
    "msg.t3": "Presentacion encendida/apagada",
    "msg.d3": "Activa o desactiva la presentacion automatica",
    "msg.t4": "Cambiar el formato del nombre de archivo",
    "msg.d4": "Cambia aqui el formato del nombre de archivo para las descargas<br/>El formato predeterminado es<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
    "msg.t5": "Silenciar videos",
    "msg.d5": "Los videos de posts, feed y reels se abren silenciados",
    "msg.t6": "Expandir automaticamente",
    "msg.d6": "Expande automaticamente el modal de medios despues de abrirlo",
    "mss.t1": "Silenciar historias",
    "mss.d1": "Las historias se abren silenciadas",
    "mss.t2": "Pausar historias al abrir",
    "mss.d2": "Las historias se pausan al abrirse",
    "mss.t3": "Mostrar historias individualmente",
    "mss.d3": "Las historias se muestran individualmente al abrirse",
    "d": "Descargar",
    "l": "Buscando medios...",
    "s": "Guardar",
    "sd": "Guardado",
    "c": "Cerrar",
    "u.t": "Actualizacion disponible",
    "u.i": "[instantgram] esta desactualizado. Revisa https://saschaheim.github.io/instantgram para ver las actualizaciones disponibles.",
    "u.v": "[instantgram] Version instalada: ${data.version} | Nueva actualizacion: ${data.onlineVersion}",
    "modules.update@update_successful": "[instantgram] Comprobacion de actualizacion completada.",
    "ad": "Patrocinado"
};

const ptBR: LocalizationDictionary = {
    "h.ld": "[instantgram] idioma: pt-BR\nPara mais informacoes sobre os idiomas disponiveis acesse https://saschaheim.github.io/instantgram",
    "a.wo": "Funciona apenas em instagram.com",
    "a.nf": "Voce abriu alguma postagem do Instagram? Por exemplo",
    "a.ie": "Este conteudo ainda nao e suportado.",
    "ms.t": "Configuracoes",
    "ms.a": "<span class=\"sx\">Novo:</span> Algumas alteracoes sao aplicadas imediatamente. Outras exigem reabrir o bookmarklet.",
    "ms.g": "Geral",
    "msg.t1": "Ativar posts monetizados",
    "msg.d1": "Os bloqueadores de anuncios devem estar desativados",
    "msg.t2": "Abrir download em nova aba",
    "msg.d2": "O download sera aberto em uma nova aba",
    "msg.t3": "Slideshow ligado/desligado",
    "msg.d3": "Ativa ou desativa o slideshow automatico",
    "msg.t4": "Alterar formato do nome do arquivo",
    "msg.d4": "Altere aqui o formato do nome dos downloads<br/>O formato padrao e<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
    "msg.t5": "Silenciar videos",
    "msg.d5": "Videos de posts, feed e reels sao abertos no mudo",
    "msg.t6": "Expandir automaticamente",
    "msg.d6": "Expande automaticamente o modal de midia apos abri-lo",
    "mss.t1": "Silenciar stories",
    "mss.d1": "Os stories sao abertos no mudo",
    "mss.t2": "Pausar stories ao abrir",
    "mss.d2": "Os stories sao pausados ao abrir",
    "mss.t3": "Exibir stories individualmente",
    "mss.d3": "Os stories sao exibidos individualmente ao abrir",
    "d": "Baixar",
    "l": "Buscando midia...",
    "s": "Salvar",
    "sd": "Salvo",
    "c": "Fechar",
    "u.t": "Atualizacao disponivel",
    "u.i": "[instantgram] esta desatualizado. Verifique https://saschaheim.github.io/instantgram para atualizacoes disponiveis.",
    "u.v": "[instantgram] Versao instalada: ${data.version} | Nova atualizacao: ${data.onlineVersion}",
    "modules.update@update_successful": "[instantgram] Verificacao de atualizacao concluida.",
    "ad": "Patrocinado"
};

const localization =
    locale === "de-DE" ? deDE :
        locale === "es-AR" ? esAR :
            locale === "pt-BR" ? ptBR :
                enUS;

export default localization;
