import { cssLinearGradient, sharedUiAnimations, sharedUiClasses } from "./styleShared";

const {
  modalOverlay,
  modal,
  modalContent,
  modalHeader,
  modalBody,
  modalFooter,
  modalDb,
  settings,
  loading,
  loadingSpinner,
  loadingText,
  modalShow,
  modalVisible,
} = sharedUiClasses;
const { loadingSpin } = sharedUiAnimations;

const modalCssRules = [
  `.${modalFooter} button,.${modalHeader} h5{font-family:"Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif!important;font-size:16px!important}`,
  `.${modalOverlay}{display:none!important;opacity:0!important;transition:.1s!important;position:fixed!important;inset:0!important;z-index:1000!important;background:rgba(0,0,0,.65)!important;justify-content:center!important;align-items:center!important}`,
  `.${modal}{transition:width .28s cubic-bezier(.22,.61,.36,1),transform .28s cubic-bezier(.22,.61,.36,1),box-shadow .28s cubic-bezier(.22,.61,.36,1)!important;display:inline-block!important;width:400px!important;padding:1.6px!important;z-index:1001!important;transform:translateY(0);box-shadow:none}`,
  `.${modal} select{margin-left:.8px!important;border:1px solid #dbdbdb!important;border-radius:3px!important;color:#262626!important;outline:0!important;padding:3px!important;text-align:center!important}`,
  `@media (min-width:736px){.${modal}{width:500px!important}}`,
  `.${modal}.instg-media-expanded{width:min(92vw,980px)!important;box-shadow:0 22px 60px rgba(0,0,0,.28)!important}`,
  `.${modal}.instg-media-expanded .slider-container{width:100%!important;max-width:none!important}`,
  `.${modal}.instg-media-expanded .slide img,.${modal}.instg-media-expanded .slide video{width:100%!important;height:auto!important;max-height:calc(min(78vh,760px) - 64px)!important}`,
  `.${modal}.instg-media-expanded .slide .${modalDb}{min-height:56px}`,
  `.${modalContent}{position:relative;display:flex;flex-direction:column;width:100%!important;pointer-events:auto!important;background-clip:padding-box!important;outline:0!important;transition:max-height .22s ease,width .22s ease!important}`,
  `.${modalHeader}{${cssLinearGradient}}`,
  `.${modalHeader}{color:#fff!important;border-top-left-radius:12px!important;border-top-right-radius:12px!important;padding:0 16px!important;text-align:center}`,
  `.${modalHeader} h5:nth-child(2){margin-top:-15px!important;margin-bottom:20px!important}`,
  `.${modalBody}{background:#fff!important;color:#000!important;position:relative!important;flex:1 1 auto!important;transition:background-color .28s ease,padding .28s ease}`,
  `.${modal}.instg-media-expanded .${modalBody}{padding:0!important}`,
  `.${modalBody}>img{background:#000;object-fit:scale-down}`,
  `.${modalFooter}{background-color:#fff!important;border-top:1px solid #dbdbdb!important;border-bottom-left-radius:12px!important;border-bottom-right-radius:12px!important;line-height:1.5!important;min-height:48px!important;padding:4px 8px!important;user-select:none!important;display:flex!important;align-items:center!important;justify-content:center!important}`,
  `.${modalFooter} button{width:100%!important;min-height:39px!important;background-color:transparent!important;border:0!important;outline:0!important;cursor:pointer!important}`,
  `.${modalFooter} button.active{color:#4b8db5!important}`,
  `.${modalShow}{opacity:1!important}`,
  `.${modalVisible}{display:flex!important}`,
  `.${modalDb}{color:#fff!important;${cssLinearGradient}display:block;padding:.8rem;width:100%;border:none;cursor:pointer;text-decoration:none}`,
  `.${modalDb}:focus{outline:0}`,
  `.${modalHeader} h5{color:#fff!important;margin:revert!important;display:flex;justify-content:space-between;align-items:center;height:15px}`,
  `.header-text-left{flex:1;text-align:left}`,
  `.header-text-right{flex:1;text-align:right;display:flex;justify-content:flex-end;align-items:center;gap:10px}`,
  `.header-text-middle{flex:1;text-align:center}`,
  `.header-text-middle a{color:#fff!important}`,
  `.${settings},.instg-modal-action{cursor:pointer;display:inline-flex;align-items:center;justify-content:center;color:rgba(255,255,255,.7);background-color:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.2);border-radius:.3rem;transition:color .2s,background-color .2s,border-color .2s,transform .24s ease;width:40px;height:40px;vertical-align:middle}`,
  `.${settings}:hover,.instg-modal-action:hover{color:rgba(255,255,255,.8);text-decoration:none;background-color:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3)}`,
  `.instg-modal-action.active{background-color:rgba(255,255,255,.28);border-color:rgba(255,255,255,.38);color:#fff}`,
  `.${modalBody} input{color:#000!important}`,
  `.${loading}{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;min-height:180px;padding:28px 20px;text-align:center}`,
  `.${loadingSpinner}{width:44px;height:44px;border-radius:50%;border:4px solid rgba(75,141,181,.22);border-top-color:#4b8db5;animation:${loadingSpin} 1s linear infinite}`,
  `@keyframes ${loadingSpin}{to{transform:rotate(360deg)}}`,
  `.${loadingText}{font-size:14px;font-weight:600;line-height:1.35;letter-spacing:.01em;color:#495057}`,

  `.${modal}.instg-update-modal{width:min(92vw,540px)!important;padding:0!important;box-shadow:0 18px 44px rgba(0,0,0,.2)!important;border-radius:18px!important;overflow:hidden!important}`,
  `.instg-update-modal .${modalContent}{background:#fff!important;border-radius:18px!important;overflow:hidden!important;border:0!important}`,
  `.instg-update-modal .${modalContent}:before{content:"";position:absolute;inset:0 0 auto 0;height:118px;background:linear-gradient(135deg,#6ea8c8 0%,#4b8db5 55%,#376d90 100%);pointer-events:none}`,
  `.instg-update-modal .${modalContent}:after{content:"";position:absolute;inset:0 0 auto 0;height:118px;background:linear-gradient(180deg,rgba(10,22,32,.16) 0%,rgba(10,22,32,.08) 62%,rgba(10,22,32,0) 100%);pointer-events:none}`,
  `.instg-update-modal .${modalHeader}{position:relative;color:#fff!important;padding:18px 22px 12px!important;text-align:left;background:transparent!important;box-shadow:none!important;border-radius:0!important}`,
  `.instg-update-modal .${modalHeader} h5{position:relative;z-index:1;color:#fff!important;margin:0!important;display:block;line-height:1.15;height:auto!important}`,
  `.instg-update-modal .header-text-left,.instg-update-modal .header-text-right{display:none!important}`,
  `.instg-update-modal .header-text-middle{display:block;font-size:16px;font-weight:700;letter-spacing:0;text-align:left;text-wrap:balance;color:#fff!important;text-shadow:none}`,
  `.instg-update-modal .${modalBody}{background:#fff!important}`,
  `.instg-update-modal .${modalFooter}{background:#fff!important;border-top:1px solid #eef3f7!important;min-height:72px!important;padding:12px 20px 20px!important}`,
  `.instg-update-modal .${modalFooter} button{min-height:44px!important;background:#f4f7fa!important;border:1px solid #dde7ee!important;border-radius:12px!important;color:#163042!important;font-weight:700!important;box-shadow:none!important;transition:background-color .2s ease,border-color .2s ease!important}`,
  `.instg-update-modal .${modalFooter} button:hover{background:#edf3f7!important;border-color:#cfdee9!important;transform:none!important;box-shadow:none!important}`,
  `.instg-update-modal .${modalFooter} button.active{color:#163042!important}`,
  `@media (max-width:560px){.instg-update-modal{width:min(94vw,540px)!important}.instg-update-modal .${modalHeader}{padding:16px 18px 10px!important}.instg-update-modal .${modalFooter}{padding:12px 16px 16px!important}}`,
];

export const cssModal = modalCssRules.join("");
