import { cssLinearGradient, sharedUiAnimations, sharedUiClasses } from "./styleShared";

const {
  modalOverlay,
  modal,
  modalContent,
  modalHeader,
  modalBody,
  modalFooter,
  modalDb,
  settings,
  loading,
  loadingSpinner,
  loadingText,
  modalShow,
  modalVisible,
} = sharedUiClasses;
const { loadingSpin } = sharedUiAnimations;
const FIREFOX_LITE = process.env.FIREFOX_LITE as unknown as boolean ?? false;

const modalCssRules = [
  `.${modal},.${modal} *{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif!important}`,
  `.${modal}{font-size:14px!important;line-height:1.5!important}`,
  `.${modalFooter} button,.${modalHeader} h5{font-size:16px!important}`,
  `.${modalOverlay}{display:none!important;opacity:0!important;transition:.1s!important;position:fixed!important;inset:0!important;z-index:1000!important;background:rgba(0,0,0,.65)!important;justify-content:center!important;align-items:center!important}`,
  `.${modal}{transition:width .28s cubic-bezier(.22,.61,.36,1),transform .28s cubic-bezier(.22,.61,.36,1),box-shadow .28s cubic-bezier(.22,.61,.36,1)!important;display:inline-block!important;width:400px!important;padding:1.6px!important;z-index:1001!important;transform:translateY(0);box-shadow:none}`,
  `@media (min-width:736px){.${modal}{width:640px!important}}`,
  `.${modal}.ime{width:min(92vw,980px)!important;box-shadow:0 22px 60px rgba(0,0,0,.28)!important}`,
  `.${modal}.ime .slider-container{width:100%!important;max-width:none!important}`,
  `.${modal}.ime .slide img,.${modal}.ime .slide video{width:100%!important;height:auto!important;max-height:calc(min(78vh,760px) - 64px)!important}`,
  `.${modal}.ime .${modalDb}{min-height:56px}`,
  `.${modalContent}{position:relative;display:flex;flex-direction:column;width:100%!important;pointer-events:auto!important;background-clip:padding-box!important;outline:0!important;transition:max-height .22s ease,width .22s ease!important}`,
  `.${modalHeader}{${cssLinearGradient}}`,
  `.${modalHeader}{color:#fff!important;border-top-left-radius:12px!important;border-top-right-radius:12px!important;padding:0 16px!important;text-align:center}`,
  `.${modalBody}{background:#fff!important;color:#000!important;position:relative!important;flex:1 1 auto!important;transition:background-color .28s ease,padding .28s ease}`,
  `.${modal}.ime .${modalBody}{padding:0!important}`,
  `.${modalFooter}{background-color:#f8f9fa!important;border-top:1px solid #dee2e6!important;border-bottom-left-radius:12px!important;border-bottom-right-radius:12px!important;line-height:1.5!important;min-height:48px!important;padding:4px 8px!important;user-select:none!important;display:flex!important;align-items:center!important;justify-content:center!important}`,
  `.${modalFooter} button{width:100%!important;min-height:39px!important;background-color:transparent!important;border:0!important;outline:0!important;cursor:pointer!important}`,
  `.${modalFooter} button.active{color:#4b8db5!important}`,
  `.${modalShow}{opacity:1!important}`,
  `.${modalVisible}{display:flex!important}`,
  `.${modalDb}{color:#fff!important;${cssLinearGradient}display:block;padding:.8rem;width:100%;border:none;cursor:pointer;text-decoration:none}`,
  `.${modalDb}:focus{outline:0}`,
  `.${modalHeader} h5{color:#fff!important;margin:revert!important;display:flex;justify-content:space-between;align-items:center;height:15px}`,
  `.hl{flex:1;text-align:left}`,
  `.hr{flex:1;text-align:right;display:flex;justify-content:flex-end;align-items:center;gap:10px}`,
  `.il{appearance:none;width:40px;height:40px;padding:0;color:#fff;color-scheme:light;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.25);border-radius:7px;font:700 12px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;outline:0;cursor:pointer;text-align:center;text-align-last:center}`,
  `.il:hover{color:rgba(255,255,255,.8);background-color:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3)}`,
  `.il option{text-align:center}`,
  `@supports not (-moz-appearance:none){.il option{color:#163042}}`,
  `.hm{flex:1;text-align:center}`,
  `.hm a{color:#fff!important}`,
  `.${settings},.ima{cursor:pointer;box-sizing:border-box;padding:0!important;color:rgba(255,255,255,.7);background-color:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.2);border-radius:7px;transition:color .2s,background-color .2s,border-color .2s,transform .24s ease;width:40px;height:40px;font-size:20px;font-weight:700;line-height:1}`,
  `.${settings}:hover,.ima:hover{color:rgba(255,255,255,.8);background-color:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3)}`,
  `.ima.active{background-color:rgba(255,255,255,.28);border-color:rgba(255,255,255,.38);color:#fff}`,
  `.ima svg{display:block;width:20px;height:20px;margin:auto}`,
  `.ib i{position:relative;top:-3px}`,
  `.${loading}{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;min-height:180px;padding:28px 20px;text-align:center}`,
  `.${loadingSpinner}{width:44px;height:44px;border-radius:50%;border:4px solid rgba(75,141,181,.22);border-top-color:#4b8db5;animation:${loadingSpin} 1s linear infinite}`,
  `@keyframes ${loadingSpin}{to{transform:rotate(360deg)}}`,
  `.${loadingText}{font-size:14px;font-weight:600;line-height:1.35;letter-spacing:.01em;color:#495057}`,

  ...(!FIREFOX_LITE ? [
  `.${modal}.ium,.ium .${modalContent}{border-radius:18px!important;overflow:hidden!important}`,
  `.${modal}.ium{width:min(92vw,540px)!important;padding:0!important;box-shadow:0 18px 44px rgba(0,0,0,.2)!important}`,
  `.ium .${modalContent}{background:#fff!important;border:0!important}`,
  `.ium .${modalContent}:before{content:"";position:absolute;inset:0 0 auto 0;height:118px;background:linear-gradient(135deg,#6ea8c8 0%,#4b8db5 55%,#376d90 100%);pointer-events:none}`,
  `.ium .${modalContent}:after{content:"";position:absolute;inset:0 0 auto 0;height:118px;background:linear-gradient(180deg,rgba(10,22,32,.16) 0%,rgba(10,22,32,.08) 62%,rgba(10,22,32,0) 100%);pointer-events:none}`,
  `.ium .${modalHeader}{position:relative;color:#fff!important;padding:18px 22px 12px!important;text-align:left;background:transparent!important;box-shadow:none!important;border-radius:0!important}`,
  `.ium .${modalHeader} h5{position:relative;z-index:1;color:#fff!important;margin:0!important;display:block;line-height:1.15;height:auto!important}`,
  `.ium .hl,.ium .hr{display:none!important}`,
  `.ium .hm{display:block;font-size:16px;font-weight:700;letter-spacing:0;text-align:left;text-wrap:balance;color:#fff!important;text-shadow:none}`,
  `.ium .${modalBody}{background:#fff!important}`,
  `.ium .${modalFooter}{background:#f8f9fa!important;border-top:1px solid #dee2e6!important;min-height:72px!important;padding:12px 20px 20px!important}`,
  `.ium .${modalFooter} button{min-height:44px!important;background:#f4f7fa!important;border:1px solid #dde7ee!important;border-radius:12px!important;color:#163042!important;font-weight:700!important;transition:background-color .2s ease,border-color .2s ease!important}`,
  `.ium .${modalFooter} button:hover{background:#edf3f7!important;border-color:#cfdee9!important;transform:none!important}`,
  `.ium .${modalFooter} button.active{color:#163042!important}`,
  `@media (max-width:560px){.ium{width:min(94vw,540px)!important}.ium .${modalHeader}{padding:16px 18px 10px!important}.ium .${modalFooter}{padding:12px 16px 16px!important}}`,
  ] : []),
];

export const cssModal = modalCssRules.join("");
