import { cssEasing as E, cssFontStack as F, cssImportant as I, cssLinearGradient, sharedUiAnimations, sharedUiClasses } from "../shared/cssTokens";

const {
  modalOverlay,
  modal,
  modalContent,
  modalHeader,
  modalBody,
  modalFooter,
  modalDb,
  settings,
  loading,
  loadingSpinner,
  loadingText,
  modalShow,
  modalVisible,
} = sharedUiClasses;
const { loadingSpin } = sharedUiAnimations;
const FIREFOX_LITE = process.env.FIREFOX_LITE as unknown as boolean ?? false;

const modalCssRules = [
  "."+modal+",."+modal+" *{font-family:"+F+I+"}",
  "."+modal+"{font-size:14px"+I+";line-height:1.5"+I+"}",
  "."+modalFooter+" button,."+modalHeader+" h5{font-size:16px"+I+"}",
  "."+modalOverlay+"{display:none"+I+";opacity:0"+I+";transition:.1s"+I+";position:fixed"+I+";inset:0"+I+";z-index:1000"+I+";background:rgba(0,0,0,.65)"+I+";justify-content:center"+I+";align-items:center"+I+"}",
  "."+modal+"{transition:width .28s "+E+",transform .28s "+E+",box-shadow .28s "+E+I+";display:inline-block"+I+";width:400px"+I+";padding:0"+I+";z-index:1001"+I+";transform:translateY(0);border-radius:16px"+I+";background:transparent"+I+";box-shadow:0 24px 70px rgba(0,0,0,.3)"+I+"}",
  "@media (min-width:736px){."+modal+"{width:640px"+I+"}}",
  "."+modal+".ime{width:min(92vw,980px)"+I+";box-shadow:0 22px 60px rgba(0,0,0,.28)"+I+"}",
  "."+modal+".ime .slider-container{width:100%"+I+";max-width:none"+I+"}",
  "."+modal+".ime .slide img,."+modal+".ime .slide video{width:100%"+I+";height:auto"+I+";max-height:calc(min(78vh,760px) - 64px)"+I+"}",
  "."+modal+".ime ."+modalDb+"{min-height:56px}",
  "."+modalContent+"{position:relative;display:flex;flex-direction:column;width:100%"+I+";pointer-events:auto"+I+";background-clip:padding-box"+I+";outline:0"+I+";transition:max-height .22s ease,width .22s ease"+I+"}",
  "."+modalHeader+"{"+cssLinearGradient+"}",
  "."+modalHeader+"{color:#fff"+I+";border-top-left-radius:14px"+I+";border-top-right-radius:14px"+I+";padding:0 16px"+I+";text-align:center}",
  "."+modalBody+"{background:#f7f4ef"+I+";color:#101820"+I+";position:relative"+I+";flex:1 1 auto"+I+";transition:background-color .28s ease,padding .28s ease}",
  "."+modal+".ime ."+modalBody+"{padding:0"+I+"}",
  "."+modalFooter+"{background:#ebe5df"+I+";border-top:1px solid #d9d2cb"+I+";border-bottom-left-radius:14px"+I+";border-bottom-right-radius:14px"+I+";line-height:1.5"+I+";min-height:48px"+I+";padding:6px 9px"+I+";user-select:none"+I+";display:flex"+I+";align-items:center"+I+";justify-content:center"+I+"}",
  "."+modalFooter+" button{width:100%"+I+";min-height:39px"+I+";background-color:transparent"+I+";border:0"+I+";outline:0"+I+";font-weight:700"+I+";cursor:pointer"+I+"}",
  "."+modalFooter+" button.active{color:#367da3"+I+"}",
  "."+modalShow+"{opacity:1"+I+"}",
  "."+modalVisible+"{display:flex"+I+"}",
  "."+modalDb+"{color:#fff"+I+";"+cssLinearGradient+"display:block;padding:.8rem;width:100%;border:none;cursor:pointer;text-decoration:none}",
  "."+modalDb+":focus{outline:0}",
  "."+modalHeader+" h5{color:#fff"+I+";margin:revert"+I+";display:flex;justify-content:space-between;align-items:center;height:15px}",
  ".hl{flex:1;text-align:left}",
  ".igb{display:block"+I+";height:30px"+I+";width:auto"+I+";max-width:none"+I+";flex:none"+I+"}",
  ".igb .igi{fill:#101820"+I+";stroke:#fff"+I+";stroke-width:2"+I+"}",
  ".igb .igg,.igb .igt{fill:#fff"+I+"}",
  ".hr{flex:1;text-align:right;display:flex;justify-content:flex-end;align-items:center;gap:10px}",
  ".il{appearance:none;width:40px;height:40px;padding:0;color:#fff;color-scheme:light;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.25);border-radius:7px;font:700 12px "+F+";outline:0;cursor:pointer;text-align:center;text-align-last:center}",
  ".il option{text-align:center;color:#101820}",
  ".hm{flex:1;text-align:center}",
  ".hm a{color:#fff"+I+"}",
  "."+settings+",.ima{cursor:pointer;box-sizing:border-box;padding:0"+I+";color:rgba(255,255,255,.7);background-color:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.2);border-radius:7px;transition:color .2s,background-color .2s,border-color .2s,transform .24s ease;width:40px;height:40px;font-size:20px;font-weight:700;line-height:1}",
  ".il:hover,."+settings+":hover,.ima:hover{color:rgba(255,255,255,.8);background-color:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3)}",
  ".ima.active{background-color:rgba(255,255,255,.28);border-color:rgba(255,255,255,.38);color:#fff}",
  ".ima svg{display:block;width:20px;height:20px;margin:auto}",
  ".ib i{position:relative;top:-3px}",
  "."+modal+" ."+loading+"{display:grid"+I+";place-content:center"+I+";place-items:center"+I+";gap:12px"+I+";width:100%"+I+";min-height:180px"+I+";margin:0"+I+";padding:28px 20px"+I+";box-sizing:border-box"+I+";text-align:center"+I+"}",
  "."+modal+" ."+loadingSpinner+"{width:44px"+I+";height:44px"+I+";margin:0 auto"+I+";border-radius:50%"+I+";border:4px solid rgba(54,125,163,.2)"+I+";border-top-color:#367da3"+I+";box-sizing:border-box"+I+";animation:"+loadingSpin+" 1s linear infinite}",
  "@keyframes "+loadingSpin+"{to{transform:rotate(360deg)}}",
  "."+modal+" ."+loadingText+"{width:100%"+I+";margin:0"+I+";font-size:14px"+I+";font-weight:600"+I+";line-height:1.35"+I+";letter-spacing:.01em"+I+";color:#495057"+I+";text-align:center"+I+"}",

  ...(!FIREFOX_LITE ? [
  "."+modal+".ium,.ium ."+modalContent+"{border-radius:18px"+I+";overflow:hidden"+I+"}",
  "."+modal+".ium{width:min(92vw,540px)"+I+";padding:0"+I+";box-shadow:0 18px 44px rgba(0,0,0,.2)"+I+"}",
  ".ium ."+modalContent+"{background:#fff"+I+";border:0"+I+"}",
  ".ium ."+modalContent+':before{content:"";position:absolute;inset:0 0 auto 0;height:118px;'+cssLinearGradient+"pointer-events:none}",
  ".ium ."+modalContent+':after{content:"";position:absolute;inset:0 0 auto 0;height:118px;background:linear-gradient(180deg,rgba(10,22,32,.16) 0%,rgba(10,22,32,.08) 62%,rgba(10,22,32,0) 100%);pointer-events:none}',
  ".ium ."+modalHeader+"{position:relative;color:#fff"+I+";padding:18px 22px 12px"+I+";text-align:left;background:transparent"+I+";box-shadow:none"+I+";border-radius:0"+I+"}",
  ".ium ."+modalHeader+" h5{position:relative;z-index:1;color:#fff"+I+";margin:0"+I+";display:block;line-height:1.15;height:auto"+I+"}",
  ".ium .hl,.ium .hr{display:none"+I+"}",
  ".ium .hm{display:block;font-size:16px;font-weight:700;letter-spacing:0;text-align:left;text-wrap:balance;color:#fff"+I+";text-shadow:none}",
  ".ium ."+modalBody+"{background:#f7f4ef"+I+"}",
  ".ium ."+modalFooter+"{background:#ebe5df"+I+";border-top:1px solid #d9d2cb"+I+";min-height:72px"+I+";padding:12px 20px 20px"+I+"}",
  ".ium ."+modalFooter+" button{min-height:44px"+I+";background:#f7f4ef"+I+";border:1px solid #d9d2cb"+I+";border-radius:12px"+I+";color:#101820"+I+";font-weight:700"+I+";transition:background-color .2s ease,border-color .2s ease"+I+"}",
  ".ium ."+modalFooter+" button:hover{background:#fff"+I+";border-color:#bfcbd2"+I+";transform:none"+I+"}",
  ".ium ."+modalFooter+" button.active{color:#101820"+I+"}",
  "@media (max-width:560px){.ium{width:min(94vw,540px)"+I+"}.ium ."+modalHeader+"{padding:16px 18px 10px"+I+"}.ium ."+modalFooter+"{padding:12px 16px 16px"+I+"}}",
  ] : []),
];

export const cssModal = modalCssRules.join("");
