const baseLang = {
    "h.ld": "[instantgram] set language: ${LANG_DEFAULT}\nFor more information about available languages please check http://saschaheim.github.io/instantgram",
    "a.wo": "Works only on instagram.com",
    "a.nf": "Did you open any Instagram post? Like for example",
    "ms.t": "Settings",
    "ms.a": "New: Some changes apply immediately. Others require reopening the bookmarklet.",
    "ms.g": "General",
    "msg.t1": "Enable monetized posts",
    "msg.d1": "Ad blockers must be deactivated",
    "msg.t2": "Open download in new tab",
    "msg.d2": "The download will be opened in a new tab",
    "msg.t3": "Slideshow on/off",
    "msg.d3": "Enable or disable the automatic slideshow",
    "msg.t4": "Change file name format for downloads",
    "msg.d4": "Change the file name format for the downloads here<br/>The default format is<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
    "mss.t1": "Mute stories",
    "mss.d1": "Stories are muted when opened",
    "mss.t2": "Pause stories when opening",
    "mss.d2": "Stories are paused when opened",
    "mss.t3": "Display stories individually",
    "mss.d3": "Stories are displayed individually when opened",
    "d": "Download",
    "l": "The current page is being scanned for media.",
    "s": "Save",
    "sd": "Saved",
    "c": "Close",
    "u.i": "[instantgram] is outdated. Please check http://saschaheim.github.io/instantgram for available updates.",
    "u.v": "[instantgram] Installed version: ${data.version} | New update: ${data.onlineVersion}",
    "ad": "Sponsored"
} as const;

type LocalizationKey = keyof typeof baseLang;
type LocalizationMap = Record<LocalizationKey, string>;
type PartialLocalizationMap = Partial<LocalizationMap>;

const mergeLang = (overrides: PartialLocalizationMap = {}): LocalizationMap => ({
    ...baseLang,
    ...overrides,
});

const langs = {
    "en-US": mergeLang(),
    "de-DE": mergeLang({
        "h.ld": "Ausgewahlte Sprache: ${LANG_DEFAULT}\nWeitere Informationen zu den unterstutzten Sprachen findest du auf http://saschaheim.github.io/instantgram",
        "a.wo": "Funktioniert nur auf instagram.com",
        "a.nf": "Hast du einen Instagram Post geoffnet? Zum Beispiel",
        "ms.t": "Einstellungen",
        "ms.a": "Neu: Einige Anderungen gelten sofort. Andere werden erst beim erneuten Offnen des Bookmarklets ubernommen.",
        "ms.g": "Allgemein",
        "msg.t1": "Monetarisierte Beitrage aktivieren",
        "msg.d1": "Werbeblocker mussen deaktiviert sein",
        "msg.t2": "Download in neuem Tab offnen",
        "msg.d2": "Der Download wird in einem neuen Tab geoffnet",
        "msg.t3": "Slideshow ein/ausschalten",
        "msg.d3": "Aktiviere oder deaktiviere die automatische Slideshow",
        "msg.t4": "Dateinamenformat fur Downloads andern",
        "msg.d4": "Andere hier das Dateinamenformat fur die Downloads<br/>Das Standardformat ist<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "mss.t1": "Stories stummschalten",
        "mss.d1": "Beim Offnen werden Stories stummgeschaltet",
        "mss.t2": "Stories beim Offnen pausieren",
        "mss.d2": "Beim Offnen werden Stories pausiert",
        "mss.t3": "Stories einzeln anzeigen",
        "mss.d3": "Beim Offnen werden Stories einzeln angezeigt",
        "l": "Die aktuelle Seite wird nach Medien durchsucht.",
        "s": "Speichern",
        "sd": "Gespeichert",
        "c": "Schliessen",
        "u.i": "[instantgram] ist veraltet. Bitte besuche die Seite http://saschaheim.github.io/instantgram fur ein Update.",
        "u.v": "[instantgram] Installierte Version: ${data.version} | Neue Version: ${data.onlineVersion}",
        "ad": "Anzeige",
    }),
    "es-AR": mergeLang({
        "h.ld": "[instantgram] establecer idioma: ${LANG_DEFAULT}\nPara mas informacion sobre los idiomas disponibles, consulta http://saschaheim.github.io/instantgram",
        "a.wo": "Solo funciona en instagram.com",
        "a.nf": "Has abierto algun post de Instagram? Como por ejemplo",
        "ms.t": "Ajustes",
        "ms.a": "Nuevo: Algunos cambios se aplican de inmediato. Otros requieren volver a abrir el bookmarklet.",
        "msg.t1": "Habilitar publicaciones monetizadas",
        "msg.d1": "Los bloqueadores de publicidad deben estar desactivados",
        "msg.t2": "Abrir descarga en una nueva pestana",
        "msg.d2": "La descarga se abrira en una nueva pestana",
        "msg.d3": "Activar/desactivar presentacion de diapositivas",
        "msg.t4": "Cambiar el formato del nombre del archivo para descargas",
        "msg.d4": "Cambia aqui el formato del nombre de archivo para las descargas<br/>El formato predeterminado es<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "mss.t1": "Historias mudas",
        "mss.d1": "Las historias se silencian cuando se abren",
        "mss.t2": "Pausar historias al abrir",
        "mss.d2": "Las historias se pausan cuando se abren",
        "mss.t3": "Mostrar historias individualmente",
        "mss.d3": "Las historias se muestran individualmente cuando se abren",
        "d": "Descargar",
        "l": "La pagina actual se esta analizando en busca de contenido multimedia.",
        "s": "Guardar",
        "sd": "Guardado",
        "c": "Cerrar",
        "u.i": "[instantgram] esta obsoleto. Consulta http://saschaheim.github.io/instantgram para ver las actualizaciones disponibles.",
        "u.v": "[instantgram] Version instalada: ${data.version} | Nueva actualizacion: ${data.onlineVersion}",
        "ad": "Publicidad",
    }),
    "pt-BR": mergeLang({
        "h.ld": "[instantgram] idioma configurado: ${LANG_DEFAULT}\npara mais informacoes sobre os idiomas suportados, acesse http://saschaheim.github.io/instantgram",
        "a.wo": "[instantgram] somente funciona no instagram.com",
        "a.nf": "Ops, voce esta em algum post do instagram? Ex:",
        "ms.t": "Configuracoes",
        "ms.a": "Novo: Algumas alteracoes sao aplicadas imediatamente. Outras exigem reabrir o bookmarklet.",
        "ms.g": "Geral",
        "msg.t1": "Habilitar postagens monetizadas",
        "msg.d1": "Os bloqueadores de anuncios devem ser desativados",
        "msg.t2": "Abrir o download em uma nova guia",
        "msg.d2": "O download sera aberto em uma nova guia",
        "msg.t3": "Ativacao/desativacao da apresentacao de slides",
        "msg.d3": "Ativar ou desativar a apresentacao automatica de slides",
        "msg.t4": "Alterar o formato do nome do arquivo para downloads",
        "msg.d4": "Altere aqui o formato do nome do arquivo para os downloads<br/>O formato padrao e<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
        "mss.t1": "Historias mudas",
        "mss.d1": "As historias sao silenciadas quando abertas",
        "mss.t2": "Pausar historias ao abrir",
        "mss.d2": "As historias sao pausadas quando abertas",
        "mss.t3": "Exibir historias individualmente",
        "mss.d3": "As historias sao exibidas individualmente quando abertas",
        "l": "A pagina atual esta sendo analisada em busca de midia.",
        "s": "Salvar",
        "sd": "Salvo",
        "c": "Fechar",
        "u.i": "[instantgram] esta desatualizado. Acesse http://saschaheim.github.io/instantgram para atualizar",
        "u.v": "[instantgram] versao local: ${data.version} | nova versao: ${data.onlineVersion}",
        "ad": "Patrocinado",
    }),
} as const;

export type SupportedLanguage = keyof typeof langs;
export type LocalizationShape = typeof langs;

export default { langs };
